/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer User
 */
public class MathQuestions extends javax.swing.JFrame {

        String [] ques = new String[10];
         
        String [] ans = {"2","2","6", "12","20", "11", "13", "15", "17","81" };
    
     
    
    /**
     * Creates new form MathQuestions
     */
    public MathQuestions() {
        initComponents();
        
        ques[0] = "1+1=?";
        ques[1] = "1*2=?";
        ques[2] = "2*3=?";
        ques[3] = "3*4=?";
        ques[4] = "4*5=?";
        ques[5] = "5+6=?";
        ques[6] = "6+7=?";
        ques[7] = "7+8=?";
        ques[8] = "8+9=?";
        ques[9] = "9*9=?";
        
        lblQ1.setText(ques[0]);
        lblQ2.setText(ques[1]);
        lblQ3.setText(ques[2]);
        lblQ4.setText(ques[3]);
        lblQ5.setText(ques[4]);
        lblQ6.setText(ques[5]);
        lblQ7.setText(ques[6]);
        lblQ8.setText(ques[7]);
        lblQ9.setText(ques[8]);
        lblQ10.setText(ques[9]);
        
        
        
      
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lblQ1 = new javax.swing.JLabel();
        lblQ2 = new javax.swing.JLabel();
        lblQ3 = new javax.swing.JLabel();
        lblQ4 = new javax.swing.JLabel();
        lblQ5 = new javax.swing.JLabel();
        lblQ6 = new javax.swing.JLabel();
        lblQ7 = new javax.swing.JLabel();
        lblQ8 = new javax.swing.JLabel();
        lblQ9 = new javax.swing.JLabel();
        lblQ10 = new javax.swing.JLabel();
        lblA1 = new javax.swing.JLabel();
        lblA2 = new javax.swing.JLabel();
        txtQ1 = new javax.swing.JTextField();
        txtQ2 = new javax.swing.JTextField();
        txtQ3 = new javax.swing.JTextField();
        txtQ4 = new javax.swing.JTextField();
        txtQ5 = new javax.swing.JTextField();
        txtQ6 = new javax.swing.JTextField();
        txtQ7 = new javax.swing.JTextField();
        txtQ8 = new javax.swing.JTextField();
        txtQ9 = new javax.swing.JTextField();
        txtQ10 = new javax.swing.JTextField();
        lblA3 = new javax.swing.JLabel();
        lblA4 = new javax.swing.JLabel();
        lblA5 = new javax.swing.JLabel();
        lblA6 = new javax.swing.JLabel();
        lblA7 = new javax.swing.JLabel();
        lblA8 = new javax.swing.JLabel();
        lblA9 = new javax.swing.JLabel();
        lblA10 = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();
        lblCorrect = new javax.swing.JLabel();
        lblCorrectValue = new javax.swing.JLabel();

        jLabel16.setText("jLabel16");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQ1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQ1.setText("jLabel1");

        lblQ2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQ2.setText("jLabel2");

        lblQ3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQ3.setText("jLabel3");

        lblQ4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQ4.setText("jLabel4");

        lblQ5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQ5.setText("jLabel5");

        lblQ6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQ6.setText("jLabel6");

        lblQ7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQ7.setText("jLabel7");

        lblQ8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQ8.setText("jLabel8");

        lblQ9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQ9.setText("jLabel9");

        lblQ10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQ10.setText("jLabel10");

        lblA1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblA1.setName("lblA1"); // NOI18N

        lblA2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblA2.setName("lblA2"); // NOI18N

        txtQ1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQ1.setName("0"); // NOI18N

        txtQ2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQ2.setName("1"); // NOI18N

        txtQ3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQ3.setName("2"); // NOI18N

        txtQ4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQ4.setName("3"); // NOI18N

        txtQ5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQ5.setName("4"); // NOI18N

        txtQ6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQ6.setName("5"); // NOI18N

        txtQ7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQ7.setName("6"); // NOI18N

        txtQ8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQ8.setName("7"); // NOI18N

        txtQ9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQ9.setName("8"); // NOI18N

        txtQ10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQ10.setName("9"); // NOI18N

        lblA3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblA3.setName("lblA3"); // NOI18N

        lblA4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblA4.setName("lblA4"); // NOI18N

        lblA5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblA5.setName("lblA5"); // NOI18N

        lblA6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblA7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblA8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblA9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblA10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnCheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        lblCorrect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCorrect.setText("number of correct answers ");

        lblCorrectValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQ6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQ7, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQ8, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblQ3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(58, 58, 58))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblQ5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(46, 46, 46))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtQ2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(txtQ3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQ10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQ5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQ9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQ8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQ7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQ6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQ4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQ1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQ9, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQ10, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblA4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblA3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(80, 80, 80)
                                    .addComponent(lblCorrectValue, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(115, 115, 115)
                                    .addComponent(lblCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(40, 40, 40))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblA10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblA8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(302, 302, 302))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblA7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblA5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblA6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(84, 84, 84)
                                    .addComponent(btnCheck)))
                            .addContainerGap()))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblA2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblA9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblA1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(273, 273, 273))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblA1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblA2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblQ2)
                                .addComponent(txtQ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblQ3)
                                .addComponent(txtQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblA3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblA4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblQ4)
                                .addComponent(txtQ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQ5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQ5)
                            .addComponent(lblA5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQ6)
                            .addComponent(txtQ6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblA6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtQ7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblQ7))
                            .addComponent(lblA7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtQ8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQ8))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblQ9)
                                    .addComponent(txtQ9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblA9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblQ10)
                                    .addComponent(txtQ10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblA10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblA8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblCorrect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCorrectValue, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(btnCheck)))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
     
        
        
        if(btnCheck.getText().equals("Check"))
        {
            lblA1.setText(ans[0]);
            lblA2.setText(ans[1]);
            lblA3.setText(ans[2]);
            lblA4.setText(ans[3]);
            lblA5.setText(ans[4]);
            lblA6.setText(ans[5]);
            lblA7.setText(ans[6]);
            lblA8.setText(ans[7]);
            lblA9.setText(ans[8]);
            lblA10.setText(ans[9]);

            int correct = 0;
            String[] userAnswers = new String[10];
            userAnswers[0]= txtQ1.getText();
            userAnswers[1]= txtQ2.getText();
            userAnswers[2]= txtQ3.getText();
            userAnswers[3]= txtQ4.getText();
            userAnswers[4]= txtQ5.getText();
            userAnswers[5]= txtQ6.getText();
            userAnswers[6]= txtQ7.getText();
            userAnswers[7]= txtQ8.getText();
            userAnswers[8]= txtQ9.getText();
            userAnswers[9]= txtQ10.getText();

            for(int i =0; i < userAnswers.length; i++)
            {
                if(userAnswers[i].equals(ans[i]))
                {
                  correct++;  
                }
            }
        
         lblCorrectValue.setText(String.valueOf(correct));
         
         btnCheck.setText("Clear");
        }
        else if (btnCheck.getText().equals("Clear"))
        {
              
            txtQ1.setText("");
            txtQ2.setText("");
            txtQ3.setText("");
            txtQ4.setText("");
            txtQ5.setText("");
            txtQ6.setText("");
            txtQ7.setText("");
            txtQ8.setText("");
            txtQ9.setText("");
            txtQ10.setText("");

            lblA1.setText("");
            lblA2.setText("");
            lblA3.setText("");
            lblA4.setText("");
            lblA5.setText("");
            lblA6.setText("");
            lblA7.setText("");
            lblA8.setText("");
            lblA9.setText("");
            lblA10.setText("");


            lblCorrectValue.setText("");
            
            btnCheck.setText("Check");
        
        }
         
      
        
    }//GEN-LAST:event_btnCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathQuestions().setVisible(true);
            }
        });
           
        
       
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblA1;
    private javax.swing.JLabel lblA10;
    private javax.swing.JLabel lblA2;
    private javax.swing.JLabel lblA3;
    private javax.swing.JLabel lblA4;
    private javax.swing.JLabel lblA5;
    private javax.swing.JLabel lblA6;
    private javax.swing.JLabel lblA7;
    private javax.swing.JLabel lblA8;
    private javax.swing.JLabel lblA9;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblCorrectValue;
    private javax.swing.JLabel lblQ1;
    private javax.swing.JLabel lblQ10;
    private javax.swing.JLabel lblQ2;
    private javax.swing.JLabel lblQ3;
    private javax.swing.JLabel lblQ4;
    private javax.swing.JLabel lblQ5;
    private javax.swing.JLabel lblQ6;
    private javax.swing.JLabel lblQ7;
    private javax.swing.JLabel lblQ8;
    private javax.swing.JLabel lblQ9;
    private javax.swing.JTextField txtQ1;
    private javax.swing.JTextField txtQ10;
    private javax.swing.JTextField txtQ2;
    private javax.swing.JTextField txtQ3;
    private javax.swing.JTextField txtQ4;
    private javax.swing.JTextField txtQ5;
    private javax.swing.JTextField txtQ6;
    private javax.swing.JTextField txtQ7;
    private javax.swing.JTextField txtQ8;
    private javax.swing.JTextField txtQ9;
    // End of variables declaration//GEN-END:variables
}
